### Numpy Question 1

In [1]:
# Import library numpy
import numpy as np

# Array Input
array1 = np.array([1,6,9,5,8])
array2 = np.array([7,5,9,10,3,])
array3 = np.array([6,3,1,9,10,8])

# Define Function 
def display_max(a,b,c):
    maxElement1 = np.amax(a)
    maxElement2 = np.amax(b)
    maxElement3 = np.amax(c)
    
    result1 = np.where(a == np.amax(a))
    result2 = np.where(b == np.amax(b))
    result3 = np.where(c == np.amax(c))
    
    print('Max Values Index for each array')
    print(result1[0],result2[0],result3[0])

# Executing Function
display_max(array1,array2,array3)
    

Max Values Index for each array
[2] [3] [4]


### Numpy Question 3

In [5]:
# Input Array
values = [0,1, 2, 3, 4, 5, 6]
n_values = np.max(values) + 1
np.eye(n_values)[values]

# Define Function
def grade(d):
    n_values = np.max(d) + 1
    n_values2 = np.eye(n_values)[d]
    print('One Hot Encoding:')
    print(n_values2)

# Execute Function
grade(values)

One Hot Encoding:
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
